# Generated by Django 3.2.8 on 2021-10-24 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('content', models.TextField()),
                ('emotional_state', models.CharField(choices=[('Really Bad', 'REALLY_BAD'), ('Bad', 'BAD'), ('Average', 'AVERAGE'), ('Good', 'GOOD'), ('Great', 'GREAT')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
