# Generated by Django 3.2.8 on 2021-10-30 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='emotional_state',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
