# Generated by Django 3.2.8 on 2021-12-11 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211030_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='content',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='rating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='EntryParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='project.journalentry')),
                ('labels', models.ManyToManyField(related_name='paragraphs', to='project.Label')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
